# Generated by Django 5.0.7 on 2024-07-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('KG', 'Бишкек'), ('KG', 'Ош'), ('KG', 'Джалал-Абад')], max_length=2, verbose_name='Страна'),
        ),
    ]
