# Generated by Django 5.0.7 on 2024-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('KG', 'Бишкек'), ('KG', 'Ош'), ('KG', 'Джалал-Абад')], max_length=100, verbose_name='Страна'),
        ),
    ]
