# Generated by Django 5.0.7 on 2024-07-25 18:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0008_alter_user_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loscation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='poligon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.polygon'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scooter', to='Apps.scooter', verbose_name='Самокат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_for_user', to='Apps.user', verbose_name='Миссия для user')),
            ],
        ),
    ]
