# Generated by Django 5.0.7 on 2024-07-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0010_delete_polygon_start_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='prioriti',
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Приоритет'),
        ),
    ]
