# Generated by Django 5.0.7 on 2024-07-24 05:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon_start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='polygon',
        ),
    ]
