# Generated by Django 5.0.7 on 2024-07-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_polygon_start_remove_user_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
