# Generated by Django 5.0.7 on 2024-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_user_contacts_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('KG', 'Бишкек'), ('KG', 'Ош'), ('KG', 'Джалал-Абад')], max_length=100, verbose_name='Регион'),
        ),
    ]
