# Generated by Django 5.0.7 on 2024-07-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Контакты'),
        ),
    ]
