# Generated by Django 5.0.7 on 2024-07-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0009_loscation_user_poligon_mission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polygon_start',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='loscation',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Миссия', 'verbose_name_plural': 'Миссии'},
        ),
        migrations.AlterModelOptions(
            name='polygon',
            options={'verbose_name': 'Полигон', 'verbose_name_plural': 'Полигоны'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='scooter',
            options={'verbose_name': 'Самокат', 'verbose_name_plural': 'Самокаты'},
        ),
        migrations.AddField(
            model_name='mission',
            name='prioriti',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
    ]
